### ISSUE TITLE
interface sh

### ISSUE THREAD

**Issue by bkoj-arch** [bkoj-arch/medicaments#1]
il faut terminer l'interface en rajoutant les commandes SQL

DOC pour aider: https://mariadb.com/kb/en/mysql-command-line-client/

pourquoi pensez a commencer l'interface python

**Comment by bkoj-arch** [comment]
il faudrait finir ca avant la fin de semaine!

**Comment by KerGaby** [comment]
Ok je regarde ça mais je promets rien !!!!
